// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bytecode.dart';
import 'api/engine.dart';
import 'api/error.dart';
import 'api/runtime.dart';
import 'api/source.dart';
import 'api/value.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class LibFjsApiImplPlatform extends BaseApiImpl<LibFjsWire> {
  LibFjsApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_JsAsyncContextPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContextPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_JsAsyncRuntimePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntimePtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_JsBytecodePtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecodePtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_JsContextPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContextPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_JsEnginePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEnginePtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_JsRuntimePtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntimePtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_MemoryUsagePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsagePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  JsAsyncContext
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
          dynamic raw);

  @protected
  JsAsyncRuntime
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
          dynamic raw);

  @protected
  JsBytecode
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode(
          dynamic raw);

  @protected
  JsContext
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
          dynamic raw);

  @protected
  JsEngine
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
          dynamic raw);

  @protected
  JsRuntime
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
          dynamic raw);

  @protected
  MemoryUsage
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
          dynamic raw);

  @protected
  JsAsyncContext
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
          dynamic raw);

  @protected
  JsAsyncRuntime
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
          dynamic raw);

  @protected
  JsContext
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
          dynamic raw);

  @protected
  JsEngine
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
          dynamic raw);

  @protected
  JsRuntime
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
          dynamic raw);

  @protected
  MemoryUsage
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
          dynamic raw);

  @protected
  FutureOr<JsResult> Function(JsValue)
      dco_decode_DartFn_Inputs_js_value_Output_js_result_AnyhowException(
          dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  Map<String, JsValue> dco_decode_Map_String_js_value_None(dynamic raw);

  @protected
  JsAsyncContext
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
          dynamic raw);

  @protected
  JsAsyncRuntime
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
          dynamic raw);

  @protected
  JsBytecode
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode(
          dynamic raw);

  @protected
  JsContext
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
          dynamic raw);

  @protected
  JsEngine
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
          dynamic raw);

  @protected
  JsRuntime
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
          dynamic raw);

  @protected
  MemoryUsage
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  JsBuiltinOptions dco_decode_box_autoadd_js_builtin_options(dynamic raw);

  @protected
  JsBytecodeEndianness dco_decode_box_autoadd_js_bytecode_endianness(
      dynamic raw);

  @protected
  JsCode dco_decode_box_autoadd_js_code(dynamic raw);

  @protected
  JsEngineRuntimeOptions dco_decode_box_autoadd_js_engine_runtime_options(
      dynamic raw);

  @protected
  JsError dco_decode_box_autoadd_js_error(dynamic raw);

  @protected
  JsEvalOptions dco_decode_box_autoadd_js_eval_options(dynamic raw);

  @protected
  JsModule dco_decode_box_autoadd_js_module(dynamic raw);

  @protected
  JsModuleBytecode dco_decode_box_autoadd_js_module_bytecode(dynamic raw);

  @protected
  JsModuleBytecodeBundle dco_decode_box_autoadd_js_module_bytecode_bundle(
      dynamic raw);

  @protected
  JsModuleBytecodeOptions dco_decode_box_autoadd_js_module_bytecode_options(
      dynamic raw);

  @protected
  JsScriptBytecode dco_decode_box_autoadd_js_script_bytecode(dynamic raw);

  @protected
  JsScriptBytecodeOptions dco_decode_box_autoadd_js_script_bytecode_options(
      dynamic raw);

  @protected
  JsValue dco_decode_box_autoadd_js_value(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  JsBuiltinOptions dco_decode_js_builtin_options(dynamic raw);

  @protected
  JsBytecodeEndianness dco_decode_js_bytecode_endianness(dynamic raw);

  @protected
  JsCode dco_decode_js_code(dynamic raw);

  @protected
  JsEngineRuntimeOptions dco_decode_js_engine_runtime_options(dynamic raw);

  @protected
  JsError dco_decode_js_error(dynamic raw);

  @protected
  JsEvalOptions dco_decode_js_eval_options(dynamic raw);

  @protected
  JsModule dco_decode_js_module(dynamic raw);

  @protected
  JsModuleBytecode dco_decode_js_module_bytecode(dynamic raw);

  @protected
  JsModuleBytecodeBundle dco_decode_js_module_bytecode_bundle(dynamic raw);

  @protected
  JsModuleBytecodeOptions dco_decode_js_module_bytecode_options(dynamic raw);

  @protected
  JsResult dco_decode_js_result(dynamic raw);

  @protected
  JsScriptBytecode dco_decode_js_script_bytecode(dynamic raw);

  @protected
  JsScriptBytecodeOptions dco_decode_js_script_bytecode_options(dynamic raw);

  @protected
  JsValue dco_decode_js_value(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<JsModule> dco_decode_list_js_module(dynamic raw);

  @protected
  List<JsModuleBytecode> dco_decode_list_js_module_bytecode(dynamic raw);

  @protected
  List<JsValue> dco_decode_list_js_value(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, JsValue)> dco_decode_list_record_string_js_value(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  JsBuiltinOptions? dco_decode_opt_box_autoadd_js_builtin_options(dynamic raw);

  @protected
  JsBytecodeEndianness? dco_decode_opt_box_autoadd_js_bytecode_endianness(
      dynamic raw);

  @protected
  JsEngineRuntimeOptions? dco_decode_opt_box_autoadd_js_engine_runtime_options(
      dynamic raw);

  @protected
  JsEvalOptions? dco_decode_opt_box_autoadd_js_eval_options(dynamic raw);

  @protected
  JsModuleBytecodeOptions?
      dco_decode_opt_box_autoadd_js_module_bytecode_options(dynamic raw);

  @protected
  JsScriptBytecodeOptions?
      dco_decode_opt_box_autoadd_js_script_bytecode_options(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  List<JsModule>? dco_decode_opt_list_js_module(dynamic raw);

  @protected
  List<JsValue>? dco_decode_opt_list_js_value(dynamic raw);

  @protected
  (String, JsValue) dco_decode_record_string_js_value(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  JsAsyncContext
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
          SseDeserializer deserializer);

  @protected
  JsAsyncRuntime
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
          SseDeserializer deserializer);

  @protected
  JsBytecode
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode(
          SseDeserializer deserializer);

  @protected
  JsContext
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
          SseDeserializer deserializer);

  @protected
  JsEngine
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
          SseDeserializer deserializer);

  @protected
  JsRuntime
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
          SseDeserializer deserializer);

  @protected
  MemoryUsage
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
          SseDeserializer deserializer);

  @protected
  JsAsyncContext
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
          SseDeserializer deserializer);

  @protected
  JsAsyncRuntime
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
          SseDeserializer deserializer);

  @protected
  JsContext
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
          SseDeserializer deserializer);

  @protected
  JsEngine
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
          SseDeserializer deserializer);

  @protected
  JsRuntime
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
          SseDeserializer deserializer);

  @protected
  MemoryUsage
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
          SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  Map<String, JsValue> sse_decode_Map_String_js_value_None(
      SseDeserializer deserializer);

  @protected
  JsAsyncContext
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
          SseDeserializer deserializer);

  @protected
  JsAsyncRuntime
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
          SseDeserializer deserializer);

  @protected
  JsBytecode
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode(
          SseDeserializer deserializer);

  @protected
  JsContext
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
          SseDeserializer deserializer);

  @protected
  JsEngine
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
          SseDeserializer deserializer);

  @protected
  JsRuntime
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
          SseDeserializer deserializer);

  @protected
  MemoryUsage
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  JsBuiltinOptions sse_decode_box_autoadd_js_builtin_options(
      SseDeserializer deserializer);

  @protected
  JsBytecodeEndianness sse_decode_box_autoadd_js_bytecode_endianness(
      SseDeserializer deserializer);

  @protected
  JsCode sse_decode_box_autoadd_js_code(SseDeserializer deserializer);

  @protected
  JsEngineRuntimeOptions sse_decode_box_autoadd_js_engine_runtime_options(
      SseDeserializer deserializer);

  @protected
  JsError sse_decode_box_autoadd_js_error(SseDeserializer deserializer);

  @protected
  JsEvalOptions sse_decode_box_autoadd_js_eval_options(
      SseDeserializer deserializer);

  @protected
  JsModule sse_decode_box_autoadd_js_module(SseDeserializer deserializer);

  @protected
  JsModuleBytecode sse_decode_box_autoadd_js_module_bytecode(
      SseDeserializer deserializer);

  @protected
  JsModuleBytecodeBundle sse_decode_box_autoadd_js_module_bytecode_bundle(
      SseDeserializer deserializer);

  @protected
  JsModuleBytecodeOptions sse_decode_box_autoadd_js_module_bytecode_options(
      SseDeserializer deserializer);

  @protected
  JsScriptBytecode sse_decode_box_autoadd_js_script_bytecode(
      SseDeserializer deserializer);

  @protected
  JsScriptBytecodeOptions sse_decode_box_autoadd_js_script_bytecode_options(
      SseDeserializer deserializer);

  @protected
  JsValue sse_decode_box_autoadd_js_value(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  JsBuiltinOptions sse_decode_js_builtin_options(SseDeserializer deserializer);

  @protected
  JsBytecodeEndianness sse_decode_js_bytecode_endianness(
      SseDeserializer deserializer);

  @protected
  JsCode sse_decode_js_code(SseDeserializer deserializer);

  @protected
  JsEngineRuntimeOptions sse_decode_js_engine_runtime_options(
      SseDeserializer deserializer);

  @protected
  JsError sse_decode_js_error(SseDeserializer deserializer);

  @protected
  JsEvalOptions sse_decode_js_eval_options(SseDeserializer deserializer);

  @protected
  JsModule sse_decode_js_module(SseDeserializer deserializer);

  @protected
  JsModuleBytecode sse_decode_js_module_bytecode(SseDeserializer deserializer);

  @protected
  JsModuleBytecodeBundle sse_decode_js_module_bytecode_bundle(
      SseDeserializer deserializer);

  @protected
  JsModuleBytecodeOptions sse_decode_js_module_bytecode_options(
      SseDeserializer deserializer);

  @protected
  JsResult sse_decode_js_result(SseDeserializer deserializer);

  @protected
  JsScriptBytecode sse_decode_js_script_bytecode(SseDeserializer deserializer);

  @protected
  JsScriptBytecodeOptions sse_decode_js_script_bytecode_options(
      SseDeserializer deserializer);

  @protected
  JsValue sse_decode_js_value(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<JsModule> sse_decode_list_js_module(SseDeserializer deserializer);

  @protected
  List<JsModuleBytecode> sse_decode_list_js_module_bytecode(
      SseDeserializer deserializer);

  @protected
  List<JsValue> sse_decode_list_js_value(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, JsValue)> sse_decode_list_record_string_js_value(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  JsBuiltinOptions? sse_decode_opt_box_autoadd_js_builtin_options(
      SseDeserializer deserializer);

  @protected
  JsBytecodeEndianness? sse_decode_opt_box_autoadd_js_bytecode_endianness(
      SseDeserializer deserializer);

  @protected
  JsEngineRuntimeOptions? sse_decode_opt_box_autoadd_js_engine_runtime_options(
      SseDeserializer deserializer);

  @protected
  JsEvalOptions? sse_decode_opt_box_autoadd_js_eval_options(
      SseDeserializer deserializer);

  @protected
  JsModuleBytecodeOptions?
      sse_decode_opt_box_autoadd_js_module_bytecode_options(
          SseDeserializer deserializer);

  @protected
  JsScriptBytecodeOptions?
      sse_decode_opt_box_autoadd_js_script_bytecode_options(
          SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  List<JsModule>? sse_decode_opt_list_js_module(SseDeserializer deserializer);

  @protected
  List<JsValue>? sse_decode_opt_list_js_value(SseDeserializer deserializer);

  @protected
  (String, JsValue) sse_decode_record_string_js_value(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
          JsAsyncContext self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
          JsAsyncRuntime self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode(
          JsBytecode self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
          JsContext self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
          JsEngine self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
          JsRuntime self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
          MemoryUsage self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
          JsAsyncContext self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
          JsAsyncRuntime self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
          JsContext self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
          JsEngine self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
          JsRuntime self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
          MemoryUsage self, SseSerializer serializer);

  @protected
  void sse_encode_DartFn_Inputs_js_value_Output_js_result_AnyhowException(
      FutureOr<JsResult> Function(JsValue) self, SseSerializer serializer);

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_js_value_None(
      Map<String, JsValue> self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
          JsAsyncContext self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
          JsAsyncRuntime self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode(
          JsBytecode self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
          JsContext self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
          JsEngine self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
          JsRuntime self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
          MemoryUsage self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_builtin_options(
      JsBuiltinOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_bytecode_endianness(
      JsBytecodeEndianness self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_code(JsCode self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_engine_runtime_options(
      JsEngineRuntimeOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_error(JsError self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_eval_options(
      JsEvalOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_module(
      JsModule self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_module_bytecode(
      JsModuleBytecode self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_module_bytecode_bundle(
      JsModuleBytecodeBundle self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_module_bytecode_options(
      JsModuleBytecodeOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_script_bytecode(
      JsScriptBytecode self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_script_bytecode_options(
      JsScriptBytecodeOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_js_value(JsValue self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_js_builtin_options(
      JsBuiltinOptions self, SseSerializer serializer);

  @protected
  void sse_encode_js_bytecode_endianness(
      JsBytecodeEndianness self, SseSerializer serializer);

  @protected
  void sse_encode_js_code(JsCode self, SseSerializer serializer);

  @protected
  void sse_encode_js_engine_runtime_options(
      JsEngineRuntimeOptions self, SseSerializer serializer);

  @protected
  void sse_encode_js_error(JsError self, SseSerializer serializer);

  @protected
  void sse_encode_js_eval_options(JsEvalOptions self, SseSerializer serializer);

  @protected
  void sse_encode_js_module(JsModule self, SseSerializer serializer);

  @protected
  void sse_encode_js_module_bytecode(
      JsModuleBytecode self, SseSerializer serializer);

  @protected
  void sse_encode_js_module_bytecode_bundle(
      JsModuleBytecodeBundle self, SseSerializer serializer);

  @protected
  void sse_encode_js_module_bytecode_options(
      JsModuleBytecodeOptions self, SseSerializer serializer);

  @protected
  void sse_encode_js_result(JsResult self, SseSerializer serializer);

  @protected
  void sse_encode_js_script_bytecode(
      JsScriptBytecode self, SseSerializer serializer);

  @protected
  void sse_encode_js_script_bytecode_options(
      JsScriptBytecodeOptions self, SseSerializer serializer);

  @protected
  void sse_encode_js_value(JsValue self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_js_module(List<JsModule> self, SseSerializer serializer);

  @protected
  void sse_encode_list_js_module_bytecode(
      List<JsModuleBytecode> self, SseSerializer serializer);

  @protected
  void sse_encode_list_js_value(List<JsValue> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_js_value(
      List<(String, JsValue)> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_js_builtin_options(
      JsBuiltinOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_js_bytecode_endianness(
      JsBytecodeEndianness? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_js_engine_runtime_options(
      JsEngineRuntimeOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_js_eval_options(
      JsEvalOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_js_module_bytecode_options(
      JsModuleBytecodeOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_js_script_bytecode_options(
      JsScriptBytecodeOptions? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_js_module(
      List<JsModule>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_js_value(
      List<JsValue>? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_js_value(
      (String, JsValue) self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class LibFjsWire implements BaseWire {
  factory LibFjsWire.fromExternalLibrary(ExternalLibrary lib) =>
      LibFjsWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LibFjsWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContextPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContextPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContextPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContext =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncContextPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntimePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntimePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntimePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntime =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsAsyncRuntimePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecodePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecodePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecodePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecode =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsBytecodePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContextPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContextPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContextPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContext =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsContextPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEnginePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEnginePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEngine =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsEnginePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntimePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntimePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntimePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntime =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsRuntimePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsagePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsagePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsagePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_fjs_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsage =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMemoryUsagePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
