// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'source.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JsBytecode>>
abstract class JsBytecode implements RustOpaqueInterface {
  /// Compiles an ES module into QuickJS bytecode.
  ///
  /// Compilation runs in an isolated QuickJS runtime and does not require a
  /// `JsEngine`. The returned bytecode is tied to the embedded QuickJS version
  /// and must only be loaded from trusted sources.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final bytecode = await JsBytecode.compile(
  ///   module: JsModule.path(
  ///     module: 'plugins/auth',
  ///     path: '/absolute/path/to/auth.js',
  ///   ),
  /// );
  /// ```
  static Future<JsModuleBytecode> compile(
          {required JsModule module, JsModuleBytecodeOptions? options}) =>
      LibFjs.instance.api
          .crateApiBytecodeJsBytecodeCompile(module: module, options: options);

  /// Compiles a set of ES modules into a bytecode bundle.
  ///
  /// Compilation runs in an isolated QuickJS runtime and does not require a
  /// `JsEngine`. Use this when precompiling a module graph for later
  /// declaration or execution.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final bundle = await JsBytecode.compileModuleBundle(
  ///   modules: [
  ///     JsModule.code(
  ///       module: 'plugins/main',
  ///       code: 'export { default } from "./impl";',
  ///     ),
  ///     JsModule.code(
  ///       module: 'plugins/impl',
  ///       code: 'export default () => "ready";',
  ///     ),
  ///   ],
  ///   entry: 'plugins/main',
  /// );
  /// ```
  static Future<JsModuleBytecodeBundle> compileModuleBundle(
          {required List<JsModule> modules,
          String? entry,
          JsModuleBytecodeOptions? options}) =>
      LibFjs.instance.api.crateApiBytecodeJsBytecodeCompileModuleBundle(
          modules: modules, entry: entry, options: options);

  /// Compiles a set of ES modules into a bytecode bundle synchronously.
  ///
  /// This reads any file-backed sources on the caller thread. Prefer the async
  /// variant on the Flutter UI isolate.
  ///
  /// When `entry` is provided, it should match one of the module names in
  /// `modules`. The resulting bundle can later be evaluated with
  /// `engine.evaluateBytecodeBundle(...)`.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final bundle = JsBytecode.compileModuleBundleSync(
  ///   modules: [
  ///     JsModule.code(
  ///       module: 'feature/index',
  ///       code: 'export { answer } from "./shared";',
  ///     ),
  ///     JsModule.code(
  ///       module: 'feature/shared',
  ///       code: 'export const answer = 42;',
  ///     ),
  ///   ],
  ///   entry: 'feature/index',
  /// );
  /// ```
  static JsModuleBytecodeBundle compileModuleBundleSync(
          {required List<JsModule> modules,
          String? entry,
          JsModuleBytecodeOptions? options}) =>
      LibFjs.instance.api.crateApiBytecodeJsBytecodeCompileModuleBundleSync(
          modules: modules, entry: entry, options: options);

  /// Compiles a classic global script into QuickJS bytecode.
  ///
  /// Set `options.promise` to `true` when the script should support top-level
  /// `await`.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final script = await JsBytecode.compileScript(
  ///   name: 'bootstrap.js',
  ///   source: JsCode.code('await Promise.resolve(globalThis.ready = true)'),
  ///   options: JsScriptBytecodeOptions.defaults().copyWith(promise: true),
  /// );
  /// ```
  static Future<JsScriptBytecode> compileScript(
          {required String name,
          required JsCode source,
          JsScriptBytecodeOptions? options}) =>
      LibFjs.instance.api.crateApiBytecodeJsBytecodeCompileScript(
          name: name, source: source, options: options);

  /// Compiles a classic global script into QuickJS bytecode synchronously.
  ///
  /// This is the non-module counterpart to `compile()`. The returned bytecode can
  /// later be executed with `engine.evaluateScriptBytecode(...)`.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final script = JsBytecode.compileScriptSync(
  ///   name: 'bootstrap.js',
  ///   source: JsCode.code('globalThis.version = "2.2.0";'),
  /// );
  /// ```
  static JsScriptBytecode compileScriptSync(
          {required String name,
          required JsCode source,
          JsScriptBytecodeOptions? options}) =>
      LibFjs.instance.api.crateApiBytecodeJsBytecodeCompileScriptSync(
          name: name, source: source, options: options);

  /// Compiles an ES module into QuickJS bytecode synchronously.
  ///
  /// This variant may block the caller while reading module source from disk.
  /// Prefer `compile()` on the main isolate.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final bytecode = JsBytecode.compileSync(
  ///   module: JsModule.code(
  ///     module: 'feature/main',
  ///     code: 'export default { ready: true };',
  ///   ),
  /// );
  /// ```
  static JsModuleBytecode compileSync(
          {required JsModule module, JsModuleBytecodeOptions? options}) =>
      LibFjs.instance.api.crateApiBytecodeJsBytecodeCompileSync(
          module: module, options: options);

  /// Validates serialized QuickJS ES module bytecode.
  ///
  /// Validation is structural: it ensures the bytes can be read by the embedded
  /// QuickJS version and that the embedded module name matches `module.name`.
  /// It does not declare or execute the module in any engine.
  ///
  /// ## Example
  ///
  /// ```dart
  /// await JsBytecode.validate(module: compiledModuleBytecode);
  /// ```
  static Future<void> validate({required JsModuleBytecode module}) =>
      LibFjs.instance.api.crateApiBytecodeJsBytecodeValidate(module: module);

  /// Validates a bundle of serialized QuickJS ES module bytecode.
  ///
  /// Validation is structural: it checks for duplicate module names, verifies the
  /// optional entry exists in the bundle, and validates each module payload. It does
  /// not execute modules or prove that external runtime dependencies will resolve.
  ///
  /// ## Example
  ///
  /// ```dart
  /// await JsBytecode.validateBundle(bundle: compiledBundle);
  /// ```
  static Future<void> validateBundle(
          {required JsModuleBytecodeBundle bundle}) =>
      LibFjs.instance.api
          .crateApiBytecodeJsBytecodeValidateBundle(bundle: bundle);

  /// Validates a bundle of serialized QuickJS ES module bytecode synchronously.
  ///
  /// Validation is structural: it checks for duplicate module names, verifies the
  /// optional entry exists in the bundle, and validates each module payload. It does
  /// not execute modules or prove that external runtime dependencies will resolve.
  ///
  /// ## Example
  ///
  /// ```dart
  /// JsBytecode.validateBundleSync(bundle: compiledBundle);
  /// ```
  static void validateBundleSync({required JsModuleBytecodeBundle bundle}) =>
      LibFjs.instance.api
          .crateApiBytecodeJsBytecodeValidateBundleSync(bundle: bundle);

  /// Validates serialized QuickJS script bytecode.
  ///
  /// Validation is structural: it ensures the bytes decode under the embedded
  /// QuickJS version and represent executable non-module bytecode.
  ///
  /// ## Example
  ///
  /// ```dart
  /// await JsBytecode.validateScript(script: compiledScriptBytecode);
  /// ```
  static Future<void> validateScript({required JsScriptBytecode script}) =>
      LibFjs.instance.api
          .crateApiBytecodeJsBytecodeValidateScript(script: script);

  /// Validates serialized QuickJS script bytecode synchronously.
  ///
  /// Validation is structural: it ensures the bytes decode under the embedded
  /// QuickJS version and represent executable non-module bytecode.
  ///
  /// ## Example
  ///
  /// ```dart
  /// JsBytecode.validateScriptSync(script: compiledScriptBytecode);
  /// ```
  static void validateScriptSync({required JsScriptBytecode script}) =>
      LibFjs.instance.api
          .crateApiBytecodeJsBytecodeValidateScriptSync(script: script);

  /// Validates serialized QuickJS ES module bytecode synchronously.
  ///
  /// Prefer `validate()` on the main isolate.
  ///
  /// ## Example
  ///
  /// ```dart
  /// JsBytecode.validateSync(module: compiledModuleBytecode);
  /// ```
  static void validateSync({required JsModuleBytecode module}) =>
      LibFjs.instance.api
          .crateApiBytecodeJsBytecodeValidateSync(module: module);
}
