// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'source.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `cmp`, `cmp`, `cmp`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `hash`, `hash`, `hash`, `hash`, `hash`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `partial_cmp`, `partial_cmp`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `as_path`, `bytes`, `code`, `get_raw_source_code_sync`, `get_raw_source_code`, `path`

/// Options for configuring builtin Node.js modules.
///
/// This struct provides fine-grained control over which Node.js
/// compatibility modules should be available in the runtime.
///
/// ## Example
///
/// ```dart
/// // Enable all builtins
/// final opts1 = JsBuiltinOptions.all();
///
/// // Enable only essential modules
/// final opts2 = JsBuiltinOptions.essential();
///
/// // Web-like environment
/// final opts3 = JsBuiltinOptions.web();
///
/// // Custom configuration
/// final opts4 = JsBuiltinOptions(
///   console: true,
///   timers: true,
///   fetch: true,
/// );
/// ```
@freezed
sealed class JsBuiltinOptions with _$JsBuiltinOptions {
  const JsBuiltinOptions._();
  const factory JsBuiltinOptions({
    bool? abort,
    bool? assert_,
    bool? asyncHooks,
    bool? buffer,
    bool? childProcess,
    bool? console,
    bool? crypto,
    bool? dgram,
    bool? dns,
    bool? events,
    bool? exceptions,
    bool? fetch,
    bool? fs,
    bool? https,
    bool? intl,
    bool? navigator,
    bool? net,
    bool? os,
    bool? path,
    bool? perfHooks,
    bool? process,
    bool? streamWeb,
    bool? stringDecoder,
    bool? temporal,
    bool? timers,
    bool? tty,
    bool? url,
    bool? util,
    bool? zlib,
    bool? json,
  }) = _JsBuiltinOptions;

  /// Creates builtin options with all modules enabled.
  ///
  /// This enables every available builtin module,
  /// providing maximum compatibility at the cost of larger binary size.
  ///
  /// ## Returns
  ///
  /// A `JsBuiltinOptions` instance with all modules enabled
  ///
  /// ## Example
  ///
  /// ```dart
  /// final opts = JsBuiltinOptions.all();
  /// final runtime = await JsAsyncRuntime.create(builtins: opts);
  /// ```
  static JsBuiltinOptions all() =>
      LibFjs.instance.api.crateApiSourceJsBuiltinOptionsAll();

  static Future<JsBuiltinOptions> default_() =>
      LibFjs.instance.api.crateApiSourceJsBuiltinOptionsDefault();

  /// Creates builtin options with essential modules only.
  ///
  /// Enables only the most commonly needed modules: console, timers, buffer, util, json.
  /// This provides a good balance between functionality and binary size.
  ///
  /// ## Returns
  ///
  /// A `JsBuiltinOptions` instance with essential modules
  ///
  /// ## Example
  ///
  /// ```dart
  /// final opts = JsBuiltinOptions.essential();
  /// final runtime = await JsAsyncRuntime.create(builtins: opts);
  /// ```
  static JsBuiltinOptions essential() =>
      LibFjs.instance.api.crateApiSourceJsBuiltinOptionsEssential();

  /// Creates builtin options for Node.js-like environment.
  ///
  /// Enables most Node.js-compatible modules except OS-specific ones.
  /// Suitable for server-side JavaScript applications.
  ///
  /// ## Returns
  ///
  /// A `JsBuiltinOptions` instance configured for Node.js-like environment
  ///
  /// ## Example
  ///
  /// ```dart
  /// final opts = JsBuiltinOptions.node();
  /// final runtime = await JsAsyncRuntime.create(builtins: opts);
  /// ```
  static JsBuiltinOptions node() =>
      LibFjs.instance.api.crateApiSourceJsBuiltinOptionsNode();

  /// Creates builtin options with no modules enabled.
  ///
  /// Creates a minimal runtime without any builtin modules.
  /// Use this when you want complete control over which modules are available.
  ///
  /// ## Returns
  ///
  /// A `JsBuiltinOptions` instance with no modules enabled
  ///
  /// ## Example
  ///
  /// ```dart
  /// final opts = JsBuiltinOptions.none();
  /// final runtime = await JsAsyncRuntime.create(builtins: opts);
  /// ```
  static JsBuiltinOptions none() =>
      LibFjs.instance.api.crateApiSourceJsBuiltinOptionsNone();

  /// Creates builtin options for web-like environment.
  ///
  /// Enables modules typically available in web browsers:
  /// console, timers, fetch, url, crypto, streamWeb, navigator, exceptions, intl, json.
  ///
  /// ## Returns
  ///
  /// A `JsBuiltinOptions` instance configured for web-like environment
  ///
  /// ## Example
  ///
  /// ```dart
  /// final opts = JsBuiltinOptions.web();
  /// final runtime = await JsAsyncRuntime.create(builtins: opts);
  /// ```
  static JsBuiltinOptions web() =>
      LibFjs.instance.api.crateApiSourceJsBuiltinOptionsWeb();
}

/// Byte order to use when writing QuickJS module bytecode.
///
/// Use a fixed endianness when bytecode must be shared between devices.
/// `little` is the safest default for modern mobile and desktop targets.
enum JsBytecodeEndianness {
  /// Use the current device's native endianness.
  native,

  /// Always emit little-endian bytecode.
  little,

  /// Always emit big-endian bytecode.
  big,
  ;

  static Future<JsBytecodeEndianness> default_() =>
      LibFjs.instance.api.crateApiSourceJsBytecodeEndiannessDefault();
}

@freezed
sealed class JsCode with _$JsCode {
  const JsCode._();

  /// Inline JavaScript code as a string
  const factory JsCode.code(
    String field0,
  ) = JsCode_Code;

  /// File path containing JavaScript code
  const factory JsCode.path(
    String field0,
  ) = JsCode_Path;

  /// Raw UTF-8 bytes containing JavaScript source code
  const factory JsCode.bytes(
    Uint8List field0,
  ) = JsCode_Bytes;

  /// Returns true if this is a Bytes variant.
  ///
  /// ## Returns
  ///
  /// `true` if this is a Bytes variant, `false` otherwise
  bool isBytes() => LibFjs.instance.api.crateApiSourceJsCodeIsBytes(
        that: this,
      );

  /// Returns true if this is a Code variant.
  ///
  /// ## Returns
  ///
  /// `true` if this is a Code variant, `false` otherwise
  bool isCode() => LibFjs.instance.api.crateApiSourceJsCodeIsCode(
        that: this,
      );

  /// Returns true if this is a Path variant.
  ///
  /// ## Returns
  ///
  /// `true` if this is a Path variant, `false` otherwise
  bool isPath() => LibFjs.instance.api.crateApiSourceJsCodeIsPath(
        that: this,
      );
}

/// Options for JavaScript code evaluation.
///
/// This struct provides configuration options for how JavaScript
/// code should be executed and evaluated.
///
/// ## Example
///
/// ```dart
/// // Default options
/// final opts1 = JsEvalOptions.defaults();
///
/// // With promise support
/// final opts2 = JsEvalOptions.withPromise();
///
/// // Custom options
/// final opts3 = JsEvalOptions(
///   global: true,
///   strict: true,
///   backtraceBarrier: false,
///   promise: true,
/// );
/// ```
@freezed
sealed class JsEvalOptions with _$JsEvalOptions {
  const JsEvalOptions._();
  const factory JsEvalOptions.raw({
    bool? global,
    bool? strict,
    bool? backtraceBarrier,
    bool? promise,
  }) = _JsEvalOptions;
  static Future<JsEvalOptions> default_() =>
      LibFjs.instance.api.crateApiSourceJsEvalOptionsDefault();

  /// Creates options with default values (global scope, strict mode).
  ///
  /// Default settings:
  /// - global: true
  /// - strict: true
  /// - backtraceBarrier: false
  /// - promise: false
  ///
  /// ## Returns
  ///
  /// A `JsEvalOptions` instance with default values
  ///
  /// ## Example
  ///
  /// ```dart
  /// final opts = JsEvalOptions.defaults();
  /// ```
  static JsEvalOptions defaults() =>
      LibFjs.instance.api.crateApiSourceJsEvalOptionsDefaults();

  /// Creates options for module evaluation.
  ///
  /// Module scope (not global), strict mode, with promise support.
  ///
  /// ## Returns
  ///
  /// A `JsEvalOptions` instance configured for modules
  static JsEvalOptions module() =>
      LibFjs.instance.api.crateApiSourceJsEvalOptionsModule();

  /// Creates new evaluation options with the specified parameters.
  ///
  /// ## Parameters
  ///
  /// - `global`: Whether to evaluate in global scope
  /// - `strict`: Whether to enforce strict mode
  /// - `backtraceBarrier`: Whether to create a backtrace barrier
  /// - `promise`: Whether to enable promise/async support
  ///
  /// ## Returns
  ///
  /// A new `JsEvalOptions` instance
  factory JsEvalOptions(
          {bool? global,
          bool? strict,
          bool? backtraceBarrier,
          bool? promise}) =>
      LibFjs.instance.api.crateApiSourceJsEvalOptionsNew(
          global: global,
          strict: strict,
          backtraceBarrier: backtraceBarrier,
          promise: promise);

  /// Creates options with promise support enabled.
  ///
  /// Enables top-level await and async/await support.
  ///
  /// ## Returns
  ///
  /// A `JsEvalOptions` instance with promise support
  ///
  /// ## Example
  ///
  /// ```dart
  /// final opts = JsEvalOptions.withPromise();
  /// ```
  static JsEvalOptions withPromise() =>
      LibFjs.instance.api.crateApiSourceJsEvalOptionsWithPromise();
}

/// Represents a JavaScript module.
///
/// This struct defines a module with a name and source code,
/// which can be loaded and executed in the JavaScript runtime.
///
/// `JsModule::bytes()` stores UTF-8 source bytes. Pre-compiled QuickJS bytecode
/// uses `JsModuleBytecode`.
///
/// ## Example
///
/// ```dart
/// // Create a module from inline code
/// final module = JsModule.code(
///   module: 'my-utils',
///   code: 'export const add = (a, b) => a + b;',
/// );
///
/// // Create a module from a file
/// final module2 = JsModule.path(
///   module: 'math',
///   path: '/path/to/math.js',
/// );
///
/// // Create a module from bytes
/// final module3 = JsModule.bytes(
///   module: 'binary-utils',
///   bytes: utf8.encode('export const VERSION = "1.0";'),
/// );
/// ```
@freezed
sealed class JsModule with _$JsModule {
  const JsModule._();
  const factory JsModule.raw({
    required String name,
    required JsCode source,
  }) = _JsModule;

  /// Creates a module from raw UTF-8 source bytes.
  ///
  /// The bytes are still JavaScript source text, not QuickJS bytecode.
  /// Use `JsModuleBytecode` for precompiled modules.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final module = JsModule.bytes(
  ///   module: 'embedded/config',
  ///   bytes: utf8.encode('export const env = "prod";'),
  /// );
  /// ```
  static JsModule bytes({required String module, required List<int> bytes}) =>
      LibFjs.instance.api
          .crateApiSourceJsModuleBytes(module: module, bytes: bytes);

  /// Creates a module from inline source text.
  ///
  /// This is the most convenient constructor when module code is already
  /// available in memory.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final module = JsModule.code(
  ///   module: 'feature/flags',
  ///   code: 'export const enabled = true;',
  /// );
  /// ```
  static JsModule code({required String module, required String code}) =>
      LibFjs.instance.api
          .crateApiSourceJsModuleCode(module: module, code: code);

  /// Creates a new module with the given name and source.
  ///
  /// ## Parameters
  ///
  /// - `name`: The module name
  /// - `source`: The source code
  ///
  /// ## Returns
  ///
  /// A new `JsModule` instance
  ///
  /// ## Example
  ///
  /// ```dart
  /// final module = JsModule(
  ///   name: 'math',
  ///   source: JsCode.code('export const add = (a, b) => a + b;'),
  /// );
  /// ```
  factory JsModule({required String name, required JsCode source}) =>
      LibFjs.instance.api.crateApiSourceJsModuleNew(name: name, source: source);

  /// Creates a module from a file path.
  ///
  /// Use this when the module source should be loaded lazily from disk.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final module = JsModule.path(
  ///   module: 'plugins/logger',
  ///   path: '/absolute/path/to/logger.js',
  /// );
  /// ```
  static JsModule path({required String module, required String path}) =>
      LibFjs.instance.api
          .crateApiSourceJsModulePath(module: module, path: path);
}

/// Serialized QuickJS bytecode for a single ES module.
///
/// The `name` must match the module name embedded in the bytecode when it is declared
/// or evaluated. Bytecode must be treated as trusted input and recompiled whenever the
/// embedded QuickJS engine version changes.
@freezed
sealed class JsModuleBytecode with _$JsModuleBytecode {
  const JsModuleBytecode._();
  const factory JsModuleBytecode.raw({
    required String name,
    required Uint8List bytes,
  }) = _JsModuleBytecode;

  /// Creates a new module bytecode container.
  ///
  /// Use this when loading previously persisted bytecode bytes back into FJS.
  /// The `name` must match the module name embedded in the bytecode payload.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final compiled = await JsBytecode.compile(
  ///   module: JsModule.code(
  ///     module: 'plugins/auth',
  ///     code: 'export const ready = true;',
  ///   ),
  /// );
  ///
  /// final restored = JsModuleBytecode(
  ///   name: compiled.name,
  ///   bytes: compiled.bytes,
  /// );
  /// ```
  factory JsModuleBytecode({required String name, required List<int> bytes}) =>
      LibFjs.instance.api
          .crateApiSourceJsModuleBytecodeNew(name: name, bytes: bytes);
}

/// A collection of precompiled ES modules, optionally with a designated entry module.
///
/// Bundles are useful when a feature ships as a module graph rather than a single module.
@freezed
sealed class JsModuleBytecodeBundle with _$JsModuleBytecodeBundle {
  const JsModuleBytecodeBundle._();
  const factory JsModuleBytecodeBundle.raw({
    String? entry,
    required List<JsModuleBytecode> modules,
  }) = _JsModuleBytecodeBundle;

  /// Creates a new bundle of bytecode modules.
  ///
  /// Set `entry` when the bundle will later be executed with
  /// `engine.evaluateBytecodeBundle(...)`. Leave it `null` when the bundle is
  /// only used for declaration.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final bundle = JsModuleBytecodeBundle(
  ///   entry: 'feature/index',
  ///   modules: [
  ///     featureIndexBytecode,
  ///     sharedUtilBytecode,
  ///   ],
  /// );
  /// ```
  factory JsModuleBytecodeBundle(
          {String? entry, required List<JsModuleBytecode> modules}) =>
      LibFjs.instance.api.crateApiSourceJsModuleBytecodeBundleNew(
          entry: entry, modules: modules);
}

/// Options used when compiling an ES module into QuickJS bytecode.
///
/// QuickJS bytecode is version-specific and must only be loaded from trusted sources.
/// It is useful for distributing pre-compiled modules, but it is not a security boundary.
@freezed
sealed class JsModuleBytecodeOptions with _$JsModuleBytecodeOptions {
  const JsModuleBytecodeOptions._();
  const factory JsModuleBytecodeOptions({
    JsBytecodeEndianness? endianness,
    bool? stripSource,
    bool? stripDebug,
  }) = _JsModuleBytecodeOptions;
  static Future<JsModuleBytecodeOptions> default_() =>
      LibFjs.instance.api.crateApiSourceJsModuleBytecodeOptionsDefault();

  /// Creates bytecode options suitable for distribution.
  ///
  /// Defaults:
  /// - little-endian output
  /// - `stripSource: true`
  /// - `stripDebug: true`
  ///
  /// ## Example
  ///
  /// ```dart
  /// final options = JsModuleBytecodeOptions.defaults();
  /// final bytecode = await JsBytecode.compile(
  ///   module: JsModule.code(
  ///     module: 'feature/main',
  ///     code: 'export default 42;',
  ///   ),
  ///   options: options,
  /// );
  /// ```
  static JsModuleBytecodeOptions defaults() =>
      LibFjs.instance.api.crateApiSourceJsModuleBytecodeOptionsDefaults();
}

/// Serialized QuickJS bytecode for a classic global script.
///
/// Unlike module bytecode, the `name` acts as compile-time metadata and source filename.
/// QuickJS does not expose an embedded script name that can be verified on load, so
/// validation is structural only.
@freezed
sealed class JsScriptBytecode with _$JsScriptBytecode {
  const JsScriptBytecode._();
  const factory JsScriptBytecode.raw({
    required String name,
    required Uint8List bytes,
  }) = _JsScriptBytecode;

  /// Creates a new script bytecode container.
  ///
  /// Use this when restoring previously persisted classic-script bytecode.
  /// Unlike module bytecode, the `name` is descriptive metadata and is not
  /// verified against the payload on load.
  ///
  /// ## Example
  ///
  /// ```dart
  /// final restored = JsScriptBytecode(
  ///   name: 'bootstrap.js',
  ///   bytes: storedBytes,
  /// );
  /// ```
  factory JsScriptBytecode({required String name, required List<int> bytes}) =>
      LibFjs.instance.api
          .crateApiSourceJsScriptBytecodeNew(name: name, bytes: bytes);
}

/// Options used when compiling non-module JavaScript into QuickJS bytecode.
///
/// This is intended for classic global/script evaluation, including optional top-level await.
@freezed
sealed class JsScriptBytecodeOptions with _$JsScriptBytecodeOptions {
  const JsScriptBytecodeOptions._();
  const factory JsScriptBytecodeOptions({
    JsBytecodeEndianness? endianness,
    bool? stripSource,
    bool? stripDebug,
    bool? strict,
    bool? backtraceBarrier,
    bool? promise,
  }) = _JsScriptBytecodeOptions;
  static Future<JsScriptBytecodeOptions> default_() =>
      LibFjs.instance.api.crateApiSourceJsScriptBytecodeOptionsDefault();

  /// Creates script bytecode options suitable for distribution.
  ///
  /// Defaults:
  /// - little-endian output
  /// - `stripSource: true`
  /// - `stripDebug: true`
  /// - `strict: true`
  /// - `backtraceBarrier: false`
  /// - `promise: false`
  ///
  /// ## Example
  ///
  /// ```dart
  /// final options = JsScriptBytecodeOptions.defaults().copyWith(
  ///   promise: true,
  /// );
  ///
  /// final script = await JsBytecode.compileScript(
  ///   name: 'bootstrap.js',
  ///   source: JsCode.code('await Promise.resolve("ready")'),
  ///   options: options,
  /// );
  /// ```
  static JsScriptBytecodeOptions defaults() =>
      LibFjs.instance.api.crateApiSourceJsScriptBytecodeOptionsDefaults();
}
