// Generated by fuse link. Do not edit.
import 'package:solid_fuse/solid_fuse.dart' show FuseRuntime;
import 'package:solid_fuse/solid_fuse.dart' as solid_fuse;

void registerFusePackages(FuseRuntime runtime) {
  solid_fuse.registerSolidFuse(runtime);
}
