import { existsSync, mkdirSync, writeFileSync } from "fs";
import { join, relative } from "path";
import { execSync } from "child_process";
import { defineCommand } from "citty";
import { findProjectRoot, scanFusePackages, type FusePackageInfo } from "./utils";

export const linkCommand = defineCommand({
  meta: {
    name: "link",
    description: "Scan node_modules for Fuse packages and generate Dart glue code",
  },
  run: async () => {
    const projectRoot = findProjectRoot();
    console.log(`Project root: ${projectRoot}`);

    const packages = scanFusePackages(projectRoot);
    console.log(`Found ${packages.length} Fuse package(s):`);
    for (const pkg of packages) {
      console.log(`  - ${pkg.npmName} (${pkg.dartName}) → ${pkg.registerClass}`);
    }

    generatePubspecOverrides(projectRoot, packages);
    generateFusePackagesDart(projectRoot, packages);
    runFlutterPubGet(projectRoot);

    console.log("\nDone!");
  },
});

function generatePubspecOverrides(
  projectRoot: string,
  packages: FusePackageInfo[]
) {
  const lines = ["# Generated by fuse link. Do not edit."];

  if (packages.length > 0) {
    lines.push("dependency_overrides:");
    for (const pkg of packages) {
      // Use forward slashes for cross-platform YAML compatibility
      const relPath = relative(projectRoot, join(pkg.path, pkg.dartPath)).replace(
        /\\/g,
        "/"
      );
      lines.push(`  ${pkg.dartName}:`);
      lines.push(`    path: ${relPath}`);
    }
  }

  const outPath = join(projectRoot, "pubspec_overrides.yaml");
  writeFileSync(outPath, lines.join("\n") + "\n");
  console.log(`\nWrote ${outPath}`);
}

function generateFusePackagesDart(
  projectRoot: string,
  packages: FusePackageInfo[]
) {
  const dir = join(projectRoot, "lib", "_generated");
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  const lines = ["// Generated by fuse link. Do not edit."];

  if (packages.length > 0) {
    // Imports
    for (const pkg of packages) {
      const alias = dartAlias(pkg.dartName);
      lines.push(`import 'package:${pkg.dartName}/${pkg.dartName}.dart' as ${alias};`);
    }

    lines.push("");
    lines.push("import 'package:solid_fuse/solid_fuse.dart';");
    lines.push("");
    lines.push("void registerFusePackages(FuseRuntime runtime) {");
    for (const pkg of packages) {
      const alias = dartAlias(pkg.dartName);
      lines.push(`  ${alias}.${pkg.registerClass}().register(runtime);`);
    }
    lines.push("}");
  } else {
    lines.push("");
    lines.push("import 'package:solid_fuse/solid_fuse.dart';");
    lines.push("");
    lines.push("void registerFusePackages(FuseRuntime runtime) {}");
  }

  const outPath = join(dir, "fuse_packages.dart");
  writeFileSync(outPath, lines.join("\n") + "\n");
  console.log(`Wrote ${outPath}`);
}

/**
 * Convert a Dart package name to a safe import alias.
 * e.g. "solid_fuse" → "solid_fuse", "fuse_auth" → "fuse_auth"
 */
function dartAlias(dartName: string): string {
  return dartName.replace(/-/g, "_");
}

function runFlutterPubGet(projectRoot: string) {
  console.log("\nRunning flutter pub get...");
  try {
    execSync("flutter pub get", {
      cwd: projectRoot,
      stdio: "inherit",
    });
  } catch {
    console.error("flutter pub get failed");
    process.exit(1);
  }
}
