import { existsSync, mkdirSync, writeFileSync } from "fs";
import { join, relative } from "path";
import { execSync } from "child_process";
import { defineCommand } from "citty";
import {
  findProjectRoot,
  getDartRoot,
  scanFusePackages,
  pubspecHasDependency,
  pubspecAddDependency,
  pubspecGetManagedDependencies,
  pubspecRemoveDependency,
  type FusePackageInfo,
} from "./utils";
import { loadFuseConfig } from "./config";

/**
 * Core link logic — exported so other commands (dev, build, install, remove) can call it.
 */
export async function runLink(projectRoot?: string, { pubGet = true } = {}) {
  const root = projectRoot ?? findProjectRoot();
  console.log(`Project root: ${root}`);

  const fuseConfig = await loadFuseConfig(root);
  const dartRoot = getDartRoot(root, fuseConfig);

  const packages = await scanFusePackages(root);
  console.log(`Found ${packages.length} Fuse package(s):`);
  for (const pkg of packages) {
    console.log(`  - ${pkg.npmName} (${pkg.dartName}) → ${pkg.registerClass}`);
  }

  const pubspecPath = join(dartRoot, "pubspec.yaml");
  const activeDartNames = new Set(packages.map((p) => p.dartName));

  // Add missing fuse packages to pubspec.yaml dependencies
  for (const pkg of packages) {
    if (!pubspecHasDependency(pubspecPath, pkg.dartName)) {
      pubspecAddDependency(pubspecPath, pkg.dartName);
      console.log(`  Added ${pkg.dartName} to pubspec.yaml dependencies`);
    }
  }

  // Remove stale fuse-managed dependencies no longer in node_modules
  for (const managed of pubspecGetManagedDependencies(pubspecPath)) {
    if (!activeDartNames.has(managed)) {
      pubspecRemoveDependency(pubspecPath, managed);
      console.log(`  Removed stale ${managed} from pubspec.yaml dependencies`);
    }
  }

  generatePubspecOverrides(dartRoot, packages);
  generateFusePackagesDart(dartRoot, packages);
  if (pubGet) runFlutterPubGet(dartRoot);

  console.log("\nDone!");
}

export const linkCommand = defineCommand({
  meta: {
    name: "link",
    description: "Scan node_modules for Fuse packages and generate Dart glue code",
  },
  run: async () => {
    await runLink();
  },
});

function generatePubspecOverrides(
  dartRoot: string,
  packages: FusePackageInfo[]
) {
  const lines = ["# Generated by fuse link. Do not edit.", "dependency_overrides:"];

  // solid-fuse itself is always a path override — the Dart package lives in
  // node_modules next to its npm counterpart and isn't published to pub.dev.
  const solidFusePath = relative(
    dartRoot,
    join(dartRoot, "..", "node_modules", "solid-fuse", "dart"),
  ).replace(/\\/g, "/");
  lines.push("  solid_fuse:");
  lines.push(`    path: ${solidFusePath}`);

  for (const pkg of packages) {
    const relPath = relative(dartRoot, join(pkg.path, pkg.dartPath)).replace(
      /\\/g,
      "/"
    );
    lines.push(`  ${pkg.dartName}:`);
    lines.push(`    path: ${relPath}`);
  }

  const outPath = join(dartRoot, "pubspec_overrides.yaml");
  writeFileSync(outPath, lines.join("\n") + "\n");
  console.log(`\nWrote ${outPath}`);
}

function generateFusePackagesDart(
  dartRoot: string,
  packages: FusePackageInfo[]
) {
  const dir = join(dartRoot, "lib", "_generated");
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  const lines = ["// Generated by fuse link. Do not edit."];

  // Import FuseRuntime type only (no collision with register functions)
  lines.push("import 'package:solid_fuse/solid_fuse.dart' show FuseRuntime;");

  // Aliased imports for all packages
  for (const pkg of packages) {
    const alias = dartAlias(pkg.dartName);
    lines.push(`import 'package:${pkg.dartName}/${pkg.dartName}.dart' as ${alias};`);
  }

  lines.push("");
  lines.push("void registerFusePackages(FuseRuntime runtime) {");

  for (const pkg of packages) {
    const alias = dartAlias(pkg.dartName);
    lines.push(`  ${alias}.${pkg.registerClass}(runtime);`);
  }

  lines.push("}");

  const outPath = join(dir, "fuse_packages.dart");
  writeFileSync(outPath, lines.join("\n") + "\n");
  console.log(`Wrote ${outPath}`);
}

/**
 * Convert a Dart package name to a safe import alias.
 * e.g. "solid_fuse" → "solid_fuse", "fuse_auth" → "fuse_auth"
 */
function dartAlias(dartName: string): string {
  return dartName.replace(/-/g, "_");
}

function runFlutterPubGet(dartRoot: string) {
  console.log("\nRunning flutter pub get...");
  try {
    execSync("flutter pub get", {
      cwd: dartRoot,
      stdio: "inherit",
    });
  } catch {
    console.error("flutter pub get failed");
    process.exit(1);
  }
}
