#!/usr/bin/env bun
// Generates src/icons/material.ts and src/icons/cupertino.ts by parsing
// Flutter's own icon source files. Run when Flutter SDK is updated.
//
// Usage: bun scripts/gen-icons.ts [path/to/flutter]

import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";

const flutterPath = process.argv[2] ?? `${process.env.HOME}/flutter`;
const materialSrc = `${flutterPath}/packages/flutter/lib/src/material/icons.dart`;
const cupertinoSrc = `${flutterPath}/packages/flutter/lib/src/cupertino/icons.dart`;

// Words reserved in JS/TS that can't be binding names.
// Source: ECMAScript strict-mode reserved words + some future-reserved.
const RESERVED = new Set([
  "break", "case", "catch", "class", "const", "continue", "debugger",
  "default", "delete", "do", "else", "enum", "export", "extends", "false",
  "finally", "for", "function", "if", "import", "in", "instanceof", "new",
  "null", "return", "super", "switch", "this", "throw", "true", "try",
  "typeof", "var", "void", "while", "with", "yield", "let", "static",
  "implements", "interface", "package", "private", "protected", "public",
  "await",
]);

function snakeToCamel(name: string): string {
  return name.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function safeIdentifier(snake: string): string {
  let id = snakeToCamel(snake);
  if (/^\d/.test(id)) id = "_" + id;
  if (RESERVED.has(id)) id = id + "_";
  return id;
}

interface IconEntry {
  name: string;
  codePoint: number;
  matchTextDirection: boolean;
}

// Parses lines like:
//   static const IconData home = IconData(0xe318, fontFamily: 'MaterialIcons');
// and multi-line forms:
//   static const IconData arrow_back = IconData(
//     0xe092,
//     fontFamily: 'MaterialIcons',
//     matchTextDirection: true,
//   );
function parseIcons(source: string): IconEntry[] {
  const pattern =
    /static\s+const\s+IconData\s+(\w+)\s*=\s*IconData\s*\(\s*(0x[0-9a-fA-F]+)([\s\S]*?)\);/g;
  const out: IconEntry[] = [];
  for (const m of source.matchAll(pattern)) {
    const name = m[1];
    const codePoint = parseInt(m[2], 16);
    const rest = m[3];
    const matchTextDirection = /matchTextDirection:\s*true/.test(rest);
    out.push({ name, codePoint, matchTextDirection });
  }
  return out;
}

function emitModule(
  entries: IconEntry[],
  fontFamily: string,
  fontPackage: string | null,
  sourceNote: string,
): string {
  // Deduplicate by safe identifier, keeping the first occurrence.
  const seen = new Set<string>();
  const rows: { id: string; entry: IconEntry }[] = [];
  for (const entry of entries) {
    const id = safeIdentifier(entry.name);
    if (seen.has(id)) continue;
    seen.add(id);
    rows.push({ id, entry });
  }
  rows.sort((a, b) => a.id.localeCompare(b.id));

  const header = [
    "// @generated by scripts/gen-icons.ts from Flutter SDK.",
    `// Source: ${sourceNote}`,
    "// Do not edit by hand — re-run the script to regenerate.",
    "",
    'import type { IconData } from "../types";',
    "",
  ].join("\n");

  const pkgArg = fontPackage ? `, "${fontPackage}"` : "";
  const factoryName = fontPackage ? "makeWithPkg" : "make";
  const factoryDef = fontPackage
    ? `const makeWithPkg = (codePoint: number, matchTextDirection = false): IconData => ({\n  codePoint,\n  fontFamily: ${JSON.stringify(fontFamily)},\n  fontPackage: ${JSON.stringify(fontPackage)},\n  ...(matchTextDirection && { matchTextDirection: true }),\n});`
    : `const make = (codePoint: number, matchTextDirection = false): IconData => ({\n  codePoint,\n  fontFamily: ${JSON.stringify(fontFamily)},\n  ...(matchTextDirection && { matchTextDirection: true }),\n});`;

  const lines = rows.map(({ id, entry }) => {
    const hex = "0x" + entry.codePoint.toString(16);
    const args = entry.matchTextDirection ? `${hex}, true` : hex;
    return `export const ${id} = /*#__PURE__*/ ${factoryName}(${args});`;
  });

  return [header, factoryDef, "", ...lines, ""].join("\n");
}

function main() {
  const materialSource = readFileSync(materialSrc, "utf-8");
  const materialEntries = parseIcons(materialSource);

  const cupertinoSource = readFileSync(cupertinoSrc, "utf-8");
  const cupertinoEntries = parseIcons(cupertinoSource);

  const outDir = resolve(__dirname, "../src/icons");
  mkdirSync(outDir, { recursive: true });

  const materialOut = emitModule(
    materialEntries,
    "MaterialIcons",
    null,
    "packages/flutter/lib/src/material/icons.dart",
  );
  writeFileSync(`${outDir}/material.ts`, materialOut);
  console.log(`Wrote ${materialEntries.length} Material icons to src/icons/material.ts`);

  const cupertinoOut = emitModule(
    cupertinoEntries,
    "CupertinoIcons",
    "cupertino_icons",
    "packages/flutter/lib/src/cupertino/icons.dart",
  );
  writeFileSync(`${outDir}/cupertino.ts`, cupertinoOut);
  console.log(`Wrote ${cupertinoEntries.length} Cupertino icons to src/icons/cupertino.ts`);
}

main();
